server:
  port: 8090
---
useSSL: false
spring.profiles.active: local
spring.jpa.generate-ddl: true
spring.jpa.hibernate.ddl-auto: update
spring.datasource.url: jdbc:mysql://localhost:3306/Reading_List
spring.datasource.username: root
spring.datasource.password:    

spring.datasource.driverClassName: com.mysql.jdbc.Driver
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect   
---
spring.main.banner-mode: false   
--- 
spring:
 thymeleaf:
   cache: false 
---
spring:
 profiles: development
logging:
 level:
  root: WARN
  org.springframework.security: DEBUG
---
spring:
  ssl:
    key-store: file:///path/to/mykeys.jks
    key-store-password: letmein
    key-password: letmein
---
amazon:
 associateId: habuma-20  
---
spring:
 profiles:
  active: production   
  
logging:
  path: /tmp/
  file: BookWorm.log
  level:
    root: WARN
  